// Constants for filter sorting
export const PRICE_ASCENDING = 'PRICE_ASCENDING';
export const PRICE_DESCENDING = 'PRICE_DESCENDING';
export const GUESTS_ASCENDING = 'GUESTS_ASCENDING';
export const GUESTS_DESCENDING = 'GUESTS_DESCENDING';
export const DURATION_ASCENDING = 'DURATION_ASCENDING';
export const DURATION_DESCENDING = 'DURATION_DESCENDING';